-- ============================================================================
-- Déploiement en 3 étapes (sans warehouse — description.md)
--   1) SP_DEPLOY_CREATE_DATABASE     → BD_<COUCHE>_<ENV_GRDF>
--   2) SP_DEPLOY_CREATE_SCHEMA         → schéma + rôles d'accès RA + grants
--   3) SP_DEPLOY_CREATE_FUNCTIONAL_ROLES → rôles fonctionnels RF (héritent des RA)
-- Prérequis : stored_proc.sql (LOG_DEPLOY, SP_CREATE_DATABASE, SP_CREATE_SCHEMA)
-- ============================================================================

USE ROLE SECURITYADMIN;

-- ---------------------------------------------------------------------------
-- 1) Base de données
-- ---------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE BD_ADMIN_INFRA.SH_DEPLOY.SP_DEPLOY_CREATE_DATABASE(
    P_COUCHE VARCHAR,
    P_ENV_GRDF VARCHAR
)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    V_COUCHE VARCHAR;
    V_ENV    VARCHAR;
BEGIN
    V_COUCHE := UPPER(TRIM(P_COUCHE));
    V_ENV    := UPPER(TRIM(P_ENV_GRDF));
    EXECUTE IMMEDIATE 'CALL BD_ADMIN_INFRA.SH_DEPLOY.SP_CREATE_DATABASE(''' || V_COUCHE || ''',''' || V_ENV || ''')';
    RETURN 'SUCCESS: BD_' || V_COUCHE || '_' || V_ENV;
EXCEPTION
    WHEN OTHER THEN
        RETURN 'ERROR: ' || SQLERRM;
END;
$$;

-- ---------------------------------------------------------------------------
-- 2) Schéma + rôles RA (RO, RW, OW, EX, OPS) liés au schéma
-- ---------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE BD_ADMIN_INFRA.SH_DEPLOY.SP_DEPLOY_CREATE_SCHEMA(
    P_COUCHE VARCHAR,
    P_ENV_GRDF VARCHAR,
    P_STREAM VARCHAR,
    P_ENV_PROJET VARCHAR,
    P_APP_SOURCE VARCHAR DEFAULT NULL,
    P_OFFRE VARCHAR DEFAULT NULL,
    P_USE_CASE VARCHAR DEFAULT NULL
)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    V_PROC           VARCHAR DEFAULT 'SP_DEPLOY_CREATE_SCHEMA';
    V_COUCHE         VARCHAR;
    V_ENV            VARCHAR;
    V_STREAM         VARCHAR;
    V_ENV_PROJET     VARCHAR;
    V_APP_SOURCE     VARCHAR;
    V_OFFRE          VARCHAR;
    V_USE_CASE       VARCHAR;
    V_DB_NAME        VARCHAR;
    V_SCHEMA_NAME    VARCHAR;
    V_SCHEMA_FQN     VARCHAR;
    V_SHTYPE         VARCHAR;
    V_RA_PREFIX      VARCHAR;
    V_RA_RO          VARCHAR;
    V_RA_RW          VARCHAR;
    V_RA_OW          VARCHAR;
    V_RA_EX          VARCHAR;
    V_RA_OPS         VARCHAR;
    V_CALL           VARCHAR;
    V_LOG_SQL        VARCHAR;
    V_START          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP();
    V_STEP_START     TIMESTAMP_NTZ;
    V_STEP_MS        NUMBER;
    V_TOTAL_MS       NUMBER;
BEGIN
    V_COUCHE     := UPPER(TRIM(P_COUCHE));
    V_ENV        := UPPER(TRIM(P_ENV_GRDF));
    V_STREAM     := UPPER(TRIM(P_STREAM));
    V_ENV_PROJET := UPPER(TRIM(P_ENV_PROJET));
    V_APP_SOURCE := UPPER(TRIM(COALESCE(P_APP_SOURCE, '')));
    V_OFFRE      := UPPER(TRIM(COALESCE(P_OFFRE, '')));
    V_USE_CASE   := UPPER(TRIM(COALESCE(P_USE_CASE, '')));

    V_CALL := 'CALL BD_ADMIN_INFRA.SH_DEPLOY.SP_CREATE_SCHEMA(''' || V_COUCHE || ''',''' || V_ENV || ''','''
        || V_STREAM || ''',''' || V_ENV_PROJET || ''','
        || CASE WHEN V_COUCHE = 'BRZ' THEN '''' || V_APP_SOURCE || '''' ELSE 'NULL' END || ','
        || CASE WHEN V_COUCHE = 'GLD' THEN '''' || V_OFFRE || ''',''' || V_USE_CASE || '''' ELSE 'NULL,NULL' END || ')';
    EXECUTE IMMEDIATE V_CALL;

    V_DB_NAME := 'BD_' || V_COUCHE || '_' || V_ENV;
    IF (V_COUCHE = 'BRZ') THEN
        V_SCHEMA_NAME := 'SH_' || V_STREAM || '_OE_' || V_APP_SOURCE || '_' || V_ENV_PROJET;
        V_SHTYPE := 'OE';
        V_RA_PREFIX := 'RA_' || V_COUCHE || '_' || V_STREAM || '_' || V_APP_SOURCE;
    ELSEIF (V_COUCHE = 'SLV') THEN
        V_SCHEMA_NAME := 'SH_' || V_STREAM || '_OM_' || V_ENV_PROJET;
        V_SHTYPE := 'OM';
        V_RA_PREFIX := 'RA_' || V_COUCHE || '_' || V_STREAM;
    ELSE
        V_SCHEMA_NAME := 'SH_' || V_STREAM || '_' || V_OFFRE || '_' || V_USE_CASE || '_' || V_ENV_PROJET;
        V_SHTYPE := V_OFFRE;
        V_RA_PREFIX := 'RA_' || V_COUCHE || '_' || V_STREAM || '_' || V_OFFRE || '_' || V_USE_CASE;
    END IF;

    V_RA_RO  := V_RA_PREFIX || '_RO_'  || V_ENV_PROJET;
    V_RA_RW  := V_RA_PREFIX || '_RW_'  || V_ENV_PROJET;
    V_RA_OW  := V_RA_PREFIX || '_OW_'  || V_ENV_PROJET;
    V_RA_EX  := V_RA_PREFIX || '_EX_'  || V_ENV_PROJET;
    V_RA_OPS := V_RA_PREFIX || '_OPS_' || V_ENV_PROJET;
    V_SCHEMA_FQN := V_DB_NAME || '.' || V_SCHEMA_NAME;

    V_STEP_START := CURRENT_TIMESTAMP();

    EXECUTE IMMEDIATE 'CREATE ROLE IF NOT EXISTS ' || V_RA_RO  || ' COMMENT = ''RA RO''';
    EXECUTE IMMEDIATE 'CREATE ROLE IF NOT EXISTS ' || V_RA_RW  || ' COMMENT = ''RA RW''';
    EXECUTE IMMEDIATE 'CREATE ROLE IF NOT EXISTS ' || V_RA_OW  || ' COMMENT = ''RA OW''';
    EXECUTE IMMEDIATE 'CREATE ROLE IF NOT EXISTS ' || V_RA_EX  || ' COMMENT = ''RA EX''';
    EXECUTE IMMEDIATE 'CREATE ROLE IF NOT EXISTS ' || V_RA_OPS || ' COMMENT = ''RA OPS''';

    EXECUTE IMMEDIATE 'GRANT USAGE ON DATABASE ' || V_DB_NAME || ' TO ROLE ' || V_RA_RO;
    EXECUTE IMMEDIATE 'GRANT USAGE ON DATABASE ' || V_DB_NAME || ' TO ROLE ' || V_RA_RW;
    EXECUTE IMMEDIATE 'GRANT USAGE ON DATABASE ' || V_DB_NAME || ' TO ROLE ' || V_RA_OW;
    EXECUTE IMMEDIATE 'GRANT USAGE ON DATABASE ' || V_DB_NAME || ' TO ROLE ' || V_RA_EX;
    EXECUTE IMMEDIATE 'GRANT USAGE ON DATABASE ' || V_DB_NAME || ' TO ROLE ' || V_RA_OPS;

    EXECUTE IMMEDIATE 'GRANT USAGE ON SCHEMA ' || V_SCHEMA_FQN || ' TO ROLE ' || V_RA_RO;
    EXECUTE IMMEDIATE 'GRANT SELECT ON ALL TABLES IN SCHEMA ' || V_SCHEMA_FQN || ' TO ROLE ' || V_RA_RO;
    EXECUTE IMMEDIATE 'GRANT SELECT ON FUTURE TABLES IN SCHEMA ' || V_SCHEMA_FQN || ' TO ROLE ' || V_RA_RO;
    EXECUTE IMMEDIATE 'GRANT SELECT ON ALL VIEWS IN SCHEMA ' || V_SCHEMA_FQN || ' TO ROLE ' || V_RA_RO;
    EXECUTE IMMEDIATE 'GRANT SELECT ON FUTURE VIEWS IN SCHEMA ' || V_SCHEMA_FQN || ' TO ROLE ' || V_RA_RO;

    EXECUTE IMMEDIATE 'GRANT USAGE ON SCHEMA ' || V_SCHEMA_FQN || ' TO ROLE ' || V_RA_RW;
    EXECUTE IMMEDIATE 'GRANT INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA ' || V_SCHEMA_FQN || ' TO ROLE ' || V_RA_RW;
    EXECUTE IMMEDIATE 'GRANT INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA ' || V_SCHEMA_FQN || ' TO ROLE ' || V_RA_RW;
    EXECUTE IMMEDIATE 'GRANT USAGE ON ALL STAGES IN SCHEMA ' || V_SCHEMA_FQN || ' TO ROLE ' || V_RA_RW;
    EXECUTE IMMEDIATE 'GRANT USAGE ON FUTURE STAGES IN SCHEMA ' || V_SCHEMA_FQN || ' TO ROLE ' || V_RA_RW;

    EXECUTE IMMEDIATE 'GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE FILE FORMAT, CREATE STAGE, CREATE SEQUENCE, '
        || 'CREATE FUNCTION, CREATE PROCEDURE, CREATE PIPE, CREATE STREAM, CREATE TASK ON SCHEMA ' || V_SCHEMA_FQN || ' TO ROLE ' || V_RA_OW;
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA ' || V_SCHEMA_FQN || ' TO ROLE ' || V_RA_OW;
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA ' || V_SCHEMA_FQN || ' TO ROLE ' || V_RA_OW;
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON ALL VIEWS IN SCHEMA ' || V_SCHEMA_FQN || ' TO ROLE ' || V_RA_OW;
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON FUTURE VIEWS IN SCHEMA ' || V_SCHEMA_FQN || ' TO ROLE ' || V_RA_OW;
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON ALL STAGES IN SCHEMA ' || V_SCHEMA_FQN || ' TO ROLE ' || V_RA_OW;
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON FUTURE STAGES IN SCHEMA ' || V_SCHEMA_FQN || ' TO ROLE ' || V_RA_OW;

    EXECUTE IMMEDIATE 'GRANT USAGE ON SCHEMA ' || V_SCHEMA_FQN || ' TO ROLE ' || V_RA_EX;
    EXECUTE IMMEDIATE 'GRANT USAGE ON ALL PROCEDURES IN SCHEMA ' || V_SCHEMA_FQN || ' TO ROLE ' || V_RA_EX;
    EXECUTE IMMEDIATE 'GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA ' || V_SCHEMA_FQN || ' TO ROLE ' || V_RA_EX;
    EXECUTE IMMEDIATE 'GRANT USAGE ON ALL FUNCTIONS IN SCHEMA ' || V_SCHEMA_FQN || ' TO ROLE ' || V_RA_EX;
    EXECUTE IMMEDIATE 'GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA ' || V_SCHEMA_FQN || ' TO ROLE ' || V_RA_EX;
    EXECUTE IMMEDIATE 'GRANT OPERATE ON ALL TASKS IN SCHEMA ' || V_SCHEMA_FQN || ' TO ROLE ' || V_RA_EX;
    EXECUTE IMMEDIATE 'GRANT OPERATE ON FUTURE TASKS IN SCHEMA ' || V_SCHEMA_FQN || ' TO ROLE ' || V_RA_EX;

    EXECUTE IMMEDIATE 'GRANT CREATE PIPE, CREATE STREAM, CREATE TASK ON SCHEMA ' || V_SCHEMA_FQN || ' TO ROLE ' || V_RA_OPS;
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON ALL PIPES IN SCHEMA ' || V_SCHEMA_FQN || ' TO ROLE ' || V_RA_OPS;
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON FUTURE PIPES IN SCHEMA ' || V_SCHEMA_FQN || ' TO ROLE ' || V_RA_OPS;
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON ALL STREAMS IN SCHEMA ' || V_SCHEMA_FQN || ' TO ROLE ' || V_RA_OPS;
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON FUTURE STREAMS IN SCHEMA ' || V_SCHEMA_FQN || ' TO ROLE ' || V_RA_OPS;
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON ALL TASKS IN SCHEMA ' || V_SCHEMA_FQN || ' TO ROLE ' || V_RA_OPS;
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON FUTURE TASKS IN SCHEMA ' || V_SCHEMA_FQN || ' TO ROLE ' || V_RA_OPS;

    V_STEP_MS  := DATEDIFF('millisecond', V_STEP_START, CURRENT_TIMESTAMP());
    V_TOTAL_MS := DATEDIFF('millisecond', V_START, CURRENT_TIMESTAMP());
    V_LOG_SQL := 'CALL BD_ADMIN_INFRA.SH_DEPLOY.LOG_DEPLOY(' ||
        '''' || V_PROC || ''',''INFO'',''' || V_COUCHE || ''',''' || V_SHTYPE || ''',NULL,NULL,'''
        || V_ENV_PROJET || ''',''' || V_ENV || ''',''SCHEMA_AND_RA'','
        || '''' || V_SCHEMA_FQN || ''',' || V_STEP_MS::VARCHAR || ',' || V_TOTAL_MS::VARCHAR || ')';
    EXECUTE IMMEDIATE V_LOG_SQL;

    RETURN 'SUCCESS: schéma + RA pour ' || V_SCHEMA_FQN;
EXCEPTION
    WHEN OTHER THEN
        V_TOTAL_MS := DATEDIFF('millisecond', V_START, CURRENT_TIMESTAMP());
        V_LOG_SQL := 'CALL BD_ADMIN_INFRA.SH_DEPLOY.LOG_DEPLOY(' ||
            '''' || V_PROC || ''',''ERROR'',''' || COALESCE(V_COUCHE, 'UNK') || ''',NULL,NULL,NULL,'''
            || COALESCE(V_ENV_PROJET, '') || ''',''' || COALESCE(V_ENV, '') || ''',''ERROR'','
            || '''' || REPLACE(SQLERRM, '''', '''''') || ''',' || V_TOTAL_MS::VARCHAR || ',' || V_TOTAL_MS::VARCHAR || ')';
        EXECUTE IMMEDIATE V_LOG_SQL;
        RETURN 'ERROR: ' || SQLERRM;
END;
$$;

-- ---------------------------------------------------------------------------
-- 3) Rôles fonctionnels RF uniquement (prérequis : SP_DEPLOY_CREATE_SCHEMA exécuté)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE BD_ADMIN_INFRA.SH_DEPLOY.SP_DEPLOY_CREATE_FUNCTIONAL_ROLES(
    P_COUCHE VARCHAR,
    P_ENV_GRDF VARCHAR,
    P_STREAM VARCHAR,
    P_ENV_PROJET VARCHAR,
    P_APP_SOURCE VARCHAR DEFAULT NULL,
    P_OFFRE VARCHAR DEFAULT NULL,
    P_USE_CASE VARCHAR DEFAULT NULL,
    P_CREATE_DEFAULT_RF BOOLEAN DEFAULT TRUE
)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    V_PROC        VARCHAR DEFAULT 'SP_DEPLOY_CREATE_FUNCTIONAL_ROLES';
    V_COUCHE      VARCHAR;
    V_ENV         VARCHAR;
    V_STREAM      VARCHAR;
    V_ENV_PROJET  VARCHAR;
    V_APP_SOURCE  VARCHAR;
    V_OFFRE       VARCHAR;
    V_USE_CASE    VARCHAR;
    V_DB_NAME     VARCHAR;
    V_SCHEMA_NAME VARCHAR;
    V_SCHEMA_FQN  VARCHAR;
    V_SHTYPE      VARCHAR;
    V_RA_PREFIX   VARCHAR;
    V_RF_PREFIX   VARCHAR;
    V_RA_RO       VARCHAR;
    V_RA_RW       VARCHAR;
    V_RA_OW       VARCHAR;
    V_RA_EX       VARCHAR;
    V_RA_OPS      VARCHAR;
    V_LOG_SQL     VARCHAR;
    V_START       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP();
    V_STEP_START  TIMESTAMP_NTZ;
    V_STEP_MS     NUMBER;
    V_TOTAL_MS    NUMBER;
BEGIN
    IF (NOT COALESCE(P_CREATE_DEFAULT_RF, TRUE)) THEN
        RETURN 'SKIPPED: P_CREATE_DEFAULT_RF is FALSE';
    END IF;

    V_COUCHE     := UPPER(TRIM(P_COUCHE));
    V_ENV        := UPPER(TRIM(P_ENV_GRDF));
    V_STREAM     := UPPER(TRIM(P_STREAM));
    V_ENV_PROJET := UPPER(TRIM(P_ENV_PROJET));
    V_APP_SOURCE := UPPER(TRIM(COALESCE(P_APP_SOURCE, '')));
    V_OFFRE      := UPPER(TRIM(COALESCE(P_OFFRE, '')));
    V_USE_CASE   := UPPER(TRIM(COALESCE(P_USE_CASE, '')));

    IF (V_COUCHE NOT IN ('BRZ', 'SLV', 'GLD')) THEN
        RETURN 'ERROR: P_COUCHE invalide.';
    END IF;
    IF (V_COUCHE = 'BRZ' AND V_APP_SOURCE = '') THEN
        RETURN 'ERROR: P_APP_SOURCE requis pour BRZ.';
    END IF;
    IF (V_COUCHE = 'GLD' AND (V_OFFRE = '' OR V_USE_CASE = '')) THEN
        RETURN 'ERROR: P_OFFRE et P_USE_CASE requis pour GLD.';
    END IF;

    V_DB_NAME := 'BD_' || V_COUCHE || '_' || V_ENV;
    IF (V_COUCHE = 'BRZ') THEN
        V_SCHEMA_NAME := 'SH_' || V_STREAM || '_OE_' || V_APP_SOURCE || '_' || V_ENV_PROJET;
        V_SHTYPE := 'OE';
        V_RA_PREFIX := 'RA_' || V_COUCHE || '_' || V_STREAM || '_' || V_APP_SOURCE;
        V_RF_PREFIX := 'RF_' || V_COUCHE || '_' || V_STREAM || '_' || V_APP_SOURCE;
    ELSEIF (V_COUCHE = 'SLV') THEN
        V_SCHEMA_NAME := 'SH_' || V_STREAM || '_OM_' || V_ENV_PROJET;
        V_SHTYPE := 'OM';
        V_RA_PREFIX := 'RA_' || V_COUCHE || '_' || V_STREAM;
        V_RF_PREFIX := 'RF_' || V_COUCHE || '_' || V_STREAM;
    ELSE
        V_SCHEMA_NAME := 'SH_' || V_STREAM || '_' || V_OFFRE || '_' || V_USE_CASE || '_' || V_ENV_PROJET;
        V_SHTYPE := V_OFFRE;
        V_RA_PREFIX := 'RA_' || V_COUCHE || '_' || V_STREAM || '_' || V_OFFRE || '_' || V_USE_CASE;
        V_RF_PREFIX := 'RF_' || V_COUCHE || '_' || V_STREAM || '_' || V_OFFRE || '_' || V_USE_CASE;
    END IF;

    V_RA_RO  := V_RA_PREFIX || '_RO_'  || V_ENV_PROJET;
    V_RA_RW  := V_RA_PREFIX || '_RW_'  || V_ENV_PROJET;
    V_RA_OW  := V_RA_PREFIX || '_OW_'  || V_ENV_PROJET;
    V_RA_EX  := V_RA_PREFIX || '_EX_'  || V_ENV_PROJET;
    V_RA_OPS := V_RA_PREFIX || '_OPS_' || V_ENV_PROJET;
    V_SCHEMA_FQN := V_DB_NAME || '.' || V_SCHEMA_NAME;

    V_STEP_START := CURRENT_TIMESTAMP();

    IF (V_COUCHE = 'BRZ') THEN
        EXECUTE IMMEDIATE 'CREATE ROLE IF NOT EXISTS ' || V_RF_PREFIX || '_STR_' || V_ENV_PROJET;
        EXECUTE IMMEDIATE 'CREATE ROLE IF NOT EXISTS ' || V_RF_PREFIX || '_BAT_' || V_ENV_PROJET;
        EXECUTE IMMEDIATE 'CREATE ROLE IF NOT EXISTS ' || V_RF_PREFIX || '_ANALYST_' || V_ENV_PROJET;
        EXECUTE IMMEDIATE 'CREATE ROLE IF NOT EXISTS ' || V_RF_PREFIX || '_DEVLOPPEUR_' || V_ENV_PROJET;
        EXECUTE IMMEDIATE 'CREATE ROLE IF NOT EXISTS ' || V_RF_PREFIX || '_ADMIN_' || V_ENV_PROJET;
        EXECUTE IMMEDIATE 'CREATE ROLE IF NOT EXISTS ' || V_RF_PREFIX || '_DBT_' || V_ENV_PROJET;

        EXECUTE IMMEDIATE 'GRANT ROLE ' || V_RA_RW || ' TO ROLE ' || V_RF_PREFIX || '_STR_' || V_ENV_PROJET;
        EXECUTE IMMEDIATE 'GRANT ROLE ' || V_RA_RW || ' TO ROLE ' || V_RF_PREFIX || '_BAT_' || V_ENV_PROJET;
        EXECUTE IMMEDIATE 'GRANT ROLE ' || V_RA_RO || ' TO ROLE ' || V_RF_PREFIX || '_ANALYST_' || V_ENV_PROJET;
        EXECUTE IMMEDIATE 'GRANT ROLE ' || V_RA_RW || ' TO ROLE ' || V_RF_PREFIX || '_DEVLOPPEUR_' || V_ENV_PROJET;
        EXECUTE IMMEDIATE 'GRANT ROLE ' || V_RA_OW || ' TO ROLE ' || V_RF_PREFIX || '_ADMIN_' || V_ENV_PROJET;
        EXECUTE IMMEDIATE 'GRANT ROLE ' || V_RA_OPS || ' TO ROLE ' || V_RF_PREFIX || '_ADMIN_' || V_ENV_PROJET;
        EXECUTE IMMEDIATE 'GRANT ROLE ' || V_RA_OW || ' TO ROLE ' || V_RF_PREFIX || '_DBT_' || V_ENV_PROJET;
        EXECUTE IMMEDIATE 'GRANT ROLE ' || V_RA_OPS || ' TO ROLE ' || V_RF_PREFIX || '_DBT_' || V_ENV_PROJET;
        EXECUTE IMMEDIATE 'GRANT ROLE ' || V_RA_RW || ' TO ROLE ' || V_RF_PREFIX || '_DBT_' || V_ENV_PROJET;
    ELSEIF (V_COUCHE = 'SLV') THEN
        EXECUTE IMMEDIATE 'CREATE ROLE IF NOT EXISTS ' || V_RF_PREFIX || '_DEVLOPPEUR_' || V_ENV_PROJET;
        EXECUTE IMMEDIATE 'CREATE ROLE IF NOT EXISTS ' || V_RF_PREFIX || '_ANALYST_' || V_ENV_PROJET;
        EXECUTE IMMEDIATE 'CREATE ROLE IF NOT EXISTS ' || V_RF_PREFIX || '_EX_' || V_ENV_PROJET;
        EXECUTE IMMEDIATE 'CREATE ROLE IF NOT EXISTS ' || V_RF_PREFIX || '_ADMIN_' || V_ENV_PROJET;
        EXECUTE IMMEDIATE 'CREATE ROLE IF NOT EXISTS ' || V_RF_PREFIX || '_DBT_' || V_ENV_PROJET;
        EXECUTE IMMEDIATE 'CREATE ROLE IF NOT EXISTS ' || V_RF_PREFIX || '_PBI_' || V_ENV_PROJET;

        EXECUTE IMMEDIATE 'GRANT ROLE ' || V_RA_RW || ' TO ROLE ' || V_RF_PREFIX || '_DEVLOPPEUR_' || V_ENV_PROJET;
        EXECUTE IMMEDIATE 'GRANT ROLE ' || V_RA_RO || ' TO ROLE ' || V_RF_PREFIX || '_ANALYST_' || V_ENV_PROJET;
        EXECUTE IMMEDIATE 'GRANT ROLE ' || V_RA_EX || ' TO ROLE ' || V_RF_PREFIX || '_EX_' || V_ENV_PROJET;
        EXECUTE IMMEDIATE 'GRANT ROLE ' || V_RA_OW || ' TO ROLE ' || V_RF_PREFIX || '_ADMIN_' || V_ENV_PROJET;
        EXECUTE IMMEDIATE 'GRANT ROLE ' || V_RA_OPS || ' TO ROLE ' || V_RF_PREFIX || '_ADMIN_' || V_ENV_PROJET;
        EXECUTE IMMEDIATE 'GRANT ROLE ' || V_RA_OW || ' TO ROLE ' || V_RF_PREFIX || '_DBT_' || V_ENV_PROJET;
        EXECUTE IMMEDIATE 'GRANT ROLE ' || V_RA_OPS || ' TO ROLE ' || V_RF_PREFIX || '_DBT_' || V_ENV_PROJET;
        EXECUTE IMMEDIATE 'GRANT ROLE ' || V_RA_RW || ' TO ROLE ' || V_RF_PREFIX || '_DBT_' || V_ENV_PROJET;
        EXECUTE IMMEDIATE 'GRANT ROLE ' || V_RA_RO || ' TO ROLE ' || V_RF_PREFIX || '_PBI_' || V_ENV_PROJET;
    ELSE
        EXECUTE IMMEDIATE 'CREATE ROLE IF NOT EXISTS ' || V_RF_PREFIX || '_DEVLOPPEUR_' || V_ENV_PROJET;
        EXECUTE IMMEDIATE 'CREATE ROLE IF NOT EXISTS ' || V_RF_PREFIX || '_ANALYST_' || V_ENV_PROJET;
        EXECUTE IMMEDIATE 'CREATE ROLE IF NOT EXISTS ' || V_RF_PREFIX || '_EX_' || V_ENV_PROJET;
        EXECUTE IMMEDIATE 'CREATE ROLE IF NOT EXISTS ' || V_RF_PREFIX || '_ADMIN_' || V_ENV_PROJET;
        EXECUTE IMMEDIATE 'CREATE ROLE IF NOT EXISTS ' || V_RF_PREFIX || '_PBI_' || V_ENV_PROJET;

        EXECUTE IMMEDIATE 'GRANT ROLE ' || V_RA_RW || ' TO ROLE ' || V_RF_PREFIX || '_DEVLOPPEUR_' || V_ENV_PROJET;
        EXECUTE IMMEDIATE 'GRANT ROLE ' || V_RA_RO || ' TO ROLE ' || V_RF_PREFIX || '_ANALYST_' || V_ENV_PROJET;
        EXECUTE IMMEDIATE 'GRANT ROLE ' || V_RA_EX || ' TO ROLE ' || V_RF_PREFIX || '_EX_' || V_ENV_PROJET;
        EXECUTE IMMEDIATE 'GRANT ROLE ' || V_RA_OW || ' TO ROLE ' || V_RF_PREFIX || '_ADMIN_' || V_ENV_PROJET;
        EXECUTE IMMEDIATE 'GRANT ROLE ' || V_RA_OPS || ' TO ROLE ' || V_RF_PREFIX || '_ADMIN_' || V_ENV_PROJET;
        EXECUTE IMMEDIATE 'GRANT ROLE ' || V_RA_OW || ' TO ROLE ' || V_RF_PREFIX || '_PBI_' || V_ENV_PROJET;
        EXECUTE IMMEDIATE 'GRANT ROLE ' || V_RA_OPS || ' TO ROLE ' || V_RF_PREFIX || '_PBI_' || V_ENV_PROJET;
        EXECUTE IMMEDIATE 'GRANT ROLE ' || V_RA_RW || ' TO ROLE ' || V_RF_PREFIX || '_PBI_' || V_ENV_PROJET;
    END IF;

    V_STEP_MS  := DATEDIFF('millisecond', V_STEP_START, CURRENT_TIMESTAMP());
    V_TOTAL_MS := DATEDIFF('millisecond', V_START, CURRENT_TIMESTAMP());
    V_LOG_SQL := 'CALL BD_ADMIN_INFRA.SH_DEPLOY.LOG_DEPLOY(' ||
        '''' || V_PROC || ''',''INFO'',''' || V_COUCHE || ''',''' || V_SHTYPE || ''',NULL,NULL,'''
        || V_ENV_PROJET || ''',''' || V_ENV || ''',''RF_ONLY'','
        || '''' || V_SCHEMA_FQN || ''',' || V_STEP_MS::VARCHAR || ',' || V_TOTAL_MS::VARCHAR || ')';
    EXECUTE IMMEDIATE V_LOG_SQL;

    RETURN 'SUCCESS: RF pour ' || V_SCHEMA_FQN;
EXCEPTION
    WHEN OTHER THEN
        V_TOTAL_MS := DATEDIFF('millisecond', V_START, CURRENT_TIMESTAMP());
        V_LOG_SQL := 'CALL BD_ADMIN_INFRA.SH_DEPLOY.LOG_DEPLOY(' ||
            '''' || V_PROC || ''',''ERROR'',''' || COALESCE(V_COUCHE, 'UNK') || ''',NULL,NULL,NULL,'''
            || COALESCE(V_ENV_PROJET, '') || ''',''' || COALESCE(V_ENV, '') || ''',''ERROR'','
            || '''' || REPLACE(SQLERRM, '''', '''''') || ''',' || V_TOTAL_MS::VARCHAR || ',' || V_TOTAL_MS::VARCHAR || ')';
        EXECUTE IMMEDIATE V_LOG_SQL;
        RETURN 'ERROR: ' || SQLERRM;
END;
$$;
